### ISSUE TITLE
Fork of mitcdh/docker?

### ISSUE THREAD

**Issue by jordansafer** [braydeejohnson/docker-screeps-server#1]
This looks very similar to [mitcdh/docker-screeps](https://github.com/mitcdh/docker-screeps), is it a fork?

**Comment by braydeejohnson** [comment]
Yea, I had pulled from it and made some changes that worked for my workflow. It wasn't a direct fork at the time so I didn't think to link it. I'll add a reference back to mitcdh's repo.

**Comment by jordansafer** [comment]
thanks!
